### PR TITLE
Added support for Text tag in header and footer

### PR DESCRIPTION
**Pull request by Drewan**
- DocxPackage now has a collection of DocxPackageParts to be inline with openxml structure
- Only document, header and footer package parts are included 
- Generator iterates over each DocxPackagePart
- GeneralParser can no longer assume all XDocuments will have a body element

### CODE REVIEW

**Comment by artplastika** [comment]
Thanks Drewan, good job! We have tested your changes for backward compatibility and it seems ok. Could you please increase minor version of the assembly? Then we will merge it.

**Comment by Drewan** [comment]
Awesome.  How do I do that? sorry

**Comment by artplastika** [comment]
https://github.com/tssoft/TsSoft.Docx.TemplateEngine/blob/master/TsSoft.Docx.TemplateEngine/Properties/AssemblyInfo.cs

    [assembly: AssemblyVersion("1.1.*")]

**Comment by Drewan** [comment]
Thanks

**Pull request merged**
